# Generated by Django 4.1.3 on 2022-12-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone_num', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studio.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default='0', max_digits=9)),
                ('directions', models.CharField(blank=True, max_length=500, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('studio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='studio.studio')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
    ]
